const keys = [
  {
    code: 'Backquote',
    key: '`',
    shiftKeyEN: '~',
    keyRu: 'ё',
    shiftKeyRu: 'Ё',
  },
  {
    code: 'Digit1',
    key: '1',
    shiftKeyEN: '!',
    keyRu: '1',
    shiftKeyRu: '!',
  },
  {
    code: 'Digit2',
    key: '2',
    shiftKeyEN: '@',
    keyRu: '2',
    shiftKeyRu: '"',
  },
  {
    code: 'Digit3',
    key: '3',
    shiftKeyEN: '#',
    keyRu: '3',
    shiftKeyRu: '№',
  },
  {
    code: 'Digit4',
    key: '4',
    shiftKeyEN: '$',
    keyRu: '4',
    shiftKeyRu: ';',
  },
  {
    code: 'Digit5',
    key: '5',
    shiftKeyEN: '%',
    keyRu: '5',
    shiftKeyRu: '%',
  },
  {
    code: 'Digit6',
    key: '6',
    shiftKeyEN: '^',
    keyRu: '6',
    shiftKeyRu: ':',
  },
  {
    code: 'Digit7',
    key: '7',
    shiftKeyEN: '&',
    keyRu: '7',
    shiftKeyRu: '?',
  },
  {
    code: 'Digit8',
    key: '8',
    shiftKeyEN: '*',
    keyRu: '8',
    shiftKeyRu: '*',
  },
  {
    code: 'Digit9',
    key: '9',
    shiftKeyEN: '(',
    keyRu: '9',
    shiftKeyRu: '(',
  },
  {
    code: 'Digit0',
    key: '0',
    shiftKeyEN: ')',
    keyRu: '0',
    shiftKeyRu: ')',
  },
  {
    code: 'Minus',
    key: '-',
    shiftKeyEN: '_',
    keyRu: '-',
    shiftKeyRu: '_',
  },
  {
    code: 'Equal',
    key: '=',
    shiftKeyEN: '+',
    keyRu: '=',
    shiftKeyRu: '+',
  },
  {
    code: 'Backspace',
    key: '⟵',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'Tab',
    key: '⇥ Tab',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'keyQ',
    key: 'q',
    shiftKeyEN: 'Q',
    keyRu: 'й',
    shiftKeyRu: 'Й',
  },
  {
    code: 'KeyQ',
    key: 'q',
    shiftKeyEN: 'Q',
    keyRu: 'й',
    shiftKeyRu: 'Й',
  },
  {
    code: 'KeyW',
    key: 'w',
    shiftKeyEN: 'W',
    keyRu: 'ц',
    shiftKeyRu: 'Ц',
  },
  {
    code: 'KeyE',
    key: 'e',
    shiftKeyEN: 'E',
    keyRu: 'у',
    shiftKeyRu: 'У',
  },
  {
    code: 'KeyR',
    key: 'r',
    shiftKeyEN: 'R',
    keyRu: 'к',
    shiftKeyRu: 'К',
  },
  {
    code: 'KeyT',
    key: 't',
    shiftKeyEN: 'T',
    keyRu: 'е',
    shiftKeyRu: 'Е',
  },
  {
    code: 'KeyY',
    key: 'y',
    shiftKeyEN: 'Y',
    keyRu: 'н',
    shiftKeyRu: 'Н',
  },
  {
    code: 'KeyU',
    key: 'u',
    shiftKeyEN: 'U',
    keyRu: 'г',
    shiftKeyRu: 'Г',
  },
  {
    code: 'KeyI',
    key: 'i',
    shiftKeyEN: 'I',
    keyRu: 'ш',
    shiftKeyRu: 'Ш',
  },
  {
    code: 'KeyO',
    key: 'o',
    shiftKeyEN: 'O',
    keyRu: 'щ',
    shiftKeyRu: 'Щ',
  },
  {
    code: 'KeyP',
    key: 'p',
    shiftKeyEN: 'P',
    keyRu: 'з',
    shiftKeyRu: 'З',
  },
  {
    code: 'BracketLeft',
    key: '[',
    shiftKeyEN: '{',
    keyRu: 'х',
    shiftKeyRu: 'Х',
  },
  {
    code: 'BracketRight',
    key: ']',
    shiftKeyEN: '}',
    keyRu: 'ъ',
    shiftKeyRu: 'Ъ',
  },
  {
    code: 'Backslash',
    key: '\\',
    shiftKeyEN: '|',
    keyRu: '\\',
    shiftKeyRu: '/',
  },
  {
    code: 'CapsLock',
    key: 'Caps',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'KeyA',
    key: 'a',
    shiftKeyEN: 'A',
    keyRu: 'ф',
    shiftKeyRu: 'Ф',
  },
  {
    code: 'KeyS',
    key: 's',
    shiftKeyEN: 'S',
    keyRu: 'ы',
    shiftKeyRu: 'Ы',
  },
  {
    code: 'KeyD',
    key: 'd',
    shiftKeyEN: 'D',
    keyRu: 'в',
    shiftKeyRu: 'В',
  },
  {
    code: 'KeyF',
    key: 'f',
    shiftKeyEN: 'F',
    keyRu: 'а',
    shiftKeyRu: 'А',
  },
  {
    code: 'KeyG',
    key: 'g',
    shiftKeyEN: 'G',
    keyRu: 'п',
    shiftKeyRu: 'П',
  },
  {
    code: 'KeyH',
    key: 'h',
    shiftKeyEN: 'H',
    keyRu: 'р',
    shiftKeyRu: 'Р',
  },
  {
    code: 'KeyJ',
    key: 'j',
    shiftKeyEN: 'J',
    keyRu: 'о',
    shiftKeyRu: 'О',
  },
  {
    code: 'KeyK',
    key: 'k',
    shiftKeyEN: 'K',
    keyRu: 'л',
    shiftKeyRu: 'Л',
  },
  {
    code: 'KeyL',
    key: 'l',
    shiftKeyEN: 'L',
    keyRu: 'д',
    shiftKeyRu: 'Д',
  },
  {
    code: 'Semicolon',
    key: ';',
    shiftKeyEN: ':',
    keyRu: 'ж',
    shiftKeyRu: 'Ж',
  },
  {
    code: 'Quote',
    key: '\'',
    shiftKeyEN: '"',
    keyRu: 'э',
    shiftKeyRu: 'э',
  },
  {
    code: 'Enter',
    key: 'Enter',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'ShiftLeft',
    key: 'Shift',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'KeyZ',
    key: 'z',
    shiftKeyEN: 'Z',
    keyRu: 'я',
    shiftKeyRu: 'Я',
  },
  {
    code: 'KeyX',
    key: 'x',
    shiftKeyEN: 'X',
    keyRu: 'ч',
    shiftKeyRu: 'Ч',
  },
  {
    code: 'KeyC',
    key: 'c',
    shiftKeyEN: 'C',
    keyRu: 'с',
    shiftKeyRu: 'С',
  },
  {
    code: 'KeyV',
    key: 'v',
    shiftKeyEN: 'V',
    keyRu: 'м',
    shiftKeyRu: 'М',
  },
  {
    code: 'KeyB',
    key: 'b',
    shiftKeyEN: 'B',
    keyRu: 'и',
    shiftKeyRu: 'И',
  },
  {
    code: 'KeyN',
    key: 'n',
    shiftKeyEN: 'N',
    keyRu: 'т',
    shiftKeyRu: 'Т',
  },
  {
    code: 'KeyM',
    key: 'm',
    shiftKeyEN: 'M',
    keyRu: 'ь',
    shiftKeyRu: 'Ь',
  },
  {
    code: 'Comma',
    key: ',',
    shiftKeyEN: '<',
    keyRu: 'б',
    shiftKeyRu: 'Б',
  },
  {
    code: 'Period',
    key: '.',
    shiftKeyEN: '>',
    keyRu: 'ю',
    shiftKeyRu: 'Ю',
  },
  {
    code: 'Slash',
    key: '/',
    shiftKeyEN: '?',
    keyRu: '.',
    shiftKeyRu: ',',
  },
  {
    code: 'ShiftRight',
    key: 'Shift',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'ControlLeft',
    key: 'Ctrl',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'AltLeft',
    key: 'Alt',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'Space',
    key: ' ',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'AltRight',
    key: 'Alt',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'ControlRight',
    key: 'Ctrl',
    shiftKeyEN: '',
    keyRu: '',
    shiftKeyRu: '',
    mode: 'additional',
  },
  {
    code: 'ArrowLeft',
    key: '◄',
    shiftKeyEN: '◄',
    keyRu: '◄',
    shiftKeyRu: '◄',
    mode: 'additional',
  },
  {
    code: 'ArrowUp',
    key: '▲',
    shiftKeyEN: '▲',
    keyRu: '▲',
    shiftKeyRu: '▲',
    mode: 'additional',
  },
  {
    code: 'ArrowDown',
    key: '▼',
    shiftKeyEN: '▼',
    keyRu: '▼',
    shiftKeyRu: '▼',
    mode: 'additional',
  },
  {
    code: 'ArrowRight',
    key: '►',
    shiftKeyEN: '►',
    keyRu: '►',
    shiftKeyRu: '►',
    mode: 'additional',
  },
];

export default keys;
